### ISSUE TITLE
Meet this weekend (April 2nd 2016)

### ISSUE THREAD

**Issue by CAPSAM** [REKutanaga/effective-tribble#6]
I (Kirk) would like to meet with Stephen and look into getting the input data screen written, maybe not made pretty, but at least rudimentary so we can start manipulating data. 

Also if we can figure out how to connect to it via the browser without going through visual studio.

**Comment by REKutanaga** [comment]
_agreed,_ need to set up some rudimentary interactions based in the web client.

**Comment by CAPSAM** [comment]
Cool. I'll set up the calendar
